In [ ]:
!wget  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

--2024-07-26 09:13:33--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2024-07-26 09:13:33 (75.2 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

#unzip data
unzip_data('nlp_getting_started.zip')

--2024-07-26 09:13:34--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.253.62.207, 172.253.115.207, 172.253.122.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.253.62.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.007s  

2024-07-26 09:13:34 (84.3 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
import pandas as pd
train_df=pd.read_csv('train.csv')
test_df=pd.read_csv('test.csv')
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
train_df_shuffled=train_df.sample(frac=1, random_state=42)
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [ ]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
train_df.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
len(train_df), len(test_df)

(7613, 3263)

In [ ]:
import random
random_index= random.randint(0, len(train_df)-5)
for row in train_df_shuffled[['text','target']][random_index: random_index+5].itertuples():
  _,text,target=row
  print(f'Target: {target}','(real diaster)' if target > 0 else ('not real diaster'))
  print(f'Text:\n {text}\n')
  print('----\n')

Target: 1 (real diaster)
Text:
 It's getting to be hazardous getting into this world alive. https://t.co/BJZSSw4tid

----

Target: 1 (real diaster)
Text:
 #boy #mix Ultimate #preparedness library: http://t.co/O207JyaByz Prepare Yourself For Any Catastrophe. Over 10 http://t.co/cjCtb2oCxg

----

Target: 0 not real diaster
Text:
 the apocalypse is upon us

----

Target: 1 (real diaster)
Text:
 Red Flag Warning for fire danger &amp; dry thunderstorms in Bay Area http://t.co/ugzu9iqPRW #weather #cawx by @NWSBayArea

----

Target: 1 (real diaster)
Text:
 Investigators have said a Virgin Galactic spaceship crash was caused by structural failure after the co-pilot ... http://t.co/WC69XAJIs4

----



In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
train_sentences, val_sentences, train_labels, val_labels= train_test_split(train_df_shuffled['text'].to_numpy(),
                                                                           train_df_shuffled['target'].to_numpy(),
                                                                           test_size=0.1,
                                                                           random_state=42)

In [ ]:
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [ ]:
train_sentences[:10], train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

## converting  text into numbers
by using:

**Tokenization - direct mappinr of token (a token could be a word or a character) to number**

**Embedding - create a matrix of feature vector for eac token (the size of the feature vector can be defined and this embedding can be learned)**

#Text vectorization (tokenization)

In [ ]:
train_sentences[:5]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
       "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
       'Somehow find you and I collide http://t.co/Ee8RpOahPk'],
      dtype=object)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
text_vectorizer=TextVectorization(max_tokens=None,
                                  standardize='lower_and_strip_punctuation',
                                  split='whitespace',
                                  ngrams=None,
                                  output_mode='int',
                                  output_sequence_length=None,
                                  pad_to_max_tokens=True
                                  )

ValueError: If pad_to_max_tokens is True, must set `max_tokens`. Received: max_tokens=None

In [ ]:
len(train_sentences[0].split())

7

In [ ]:
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [ ]:
max_vocab_length=10000
max_length=15
text_vectorizer= TextVectorization(max_tokens=max_vocab_length,
                                   output_mode='int',
                                   output_sequence_length=max_length)

In [ ]:
text_vectorizer.adapt(train_sentences)

In [ ]:
# create a sample sentence and tokenize it
sample_sentence= " There's a flood in my street"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [ ]:
# choose a random sentence from the traininf dataset and tokenize it
random_sentence= random.choice(train_sentences)
print(f'original text:\n {random_sentence}\n\n Vectorized version:')
text_vectorizer([random_sentence])

original text:
 Top link: Reddit's new content policy goes into effect many horrible subreddits banned or quarantined http://t.co/BjVfk1ETe9

 Vectorized version:


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 212, 1074,  878,   50,  226,  595,  512,   66,  780,  123,  395,
         918,  793,   53,  433]])>

In [ ]:
# get the unique word in the vocubulary
words_in_vocab=text_vectorizer.get_vocabulary()
top_5_words=words_in_vocab[:5]
bottom_5_words=words_in_vocab[-5:]
print(f'Most common words in the vocab: {top_5_words}')
print(f' Least common words in the vocab: {bottom_5_words}')

Most common words in the vocab: ['', '[UNK]', 'the', 'a', 'in']
 Least common words in the vocab: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


In [ ]:
len(words_in_vocab)

10000

# Creating an Embedding using Embedding layer

In [ ]:
from tensorflow.keras import layers
embedding=layers.Embedding(input_dim=max_vocab_length,
                           output_dim=128,
                           embeddings_initializer='uniform',
                           input_length=max_length)
embedding

In [ ]:
random_sentences= random.choice(train_sentences)
print(f'Original text:\n {random_sentences}\n\n\n Embedded version: ')

sample_embed = embedding( text_vectorizer([random_sentences]))
sample_embed

Original text:
 Sinking ships burning buildings &amp; Falling objects are what reminds me of the old us.


 Embedded version: 


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[ 0.01079029, -0.02723148,  0.03799163, ...,  0.00385017,
          0.027057  ,  0.03739715],
        [ 0.01219354,  0.03172114,  0.01951433, ...,  0.04993203,
          0.03925517, -0.01593509],
        [-0.00413493,  0.00194699,  0.00469799, ...,  0.03996881,
         -0.00820976, -0.04536777],
        ...,
        [-0.0344416 , -0.02631964,  0.00600898, ...,  0.03799054,
          0.01896956,  0.00022323],
        [-0.0358057 , -0.04229829, -0.04272462, ...,  0.01299964,
          0.00957952, -0.00566224],
        [ 0.02280271,  0.00179564,  0.03187025, ...,  0.02523157,
          0.01629559,  0.00856357]]], dtype=float32)>

In [ ]:
sample_embed[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([ 0.01079029, -0.02723148,  0.03799163,  0.03158819,  0.00607513,
       -0.03219245, -0.04659874,  0.0143387 ,  0.00614871,  0.02568204,
       -0.03672894,  0.00897232,  0.03010324, -0.00735594, -0.04187293,
        0.01841639,  0.03443433,  0.01176256,  0.0458368 , -0.00285637,
        0.03150243, -0.04254336, -0.02385038, -0.04447043,  0.02295884,
       -0.01502391, -0.005913  ,  0.02553013,  0.03014531, -0.01894623,
        0.02782061,  0.04147807,  0.04640954, -0.0329231 , -0.01817723,
       -0.01560762,  0.00996778,  0.02103646, -0.0159309 ,  0.00285954,
       -0.01557392,  0.01929494,  0.03747399,  0.01348568,  0.00060298,
       -0.04567203, -0.01995287, -0.02857232, -0.00960092,  0.00755832,
       -0.04177805,  0.0434984 ,  0.00156895,  0.00550608,  0.0334825 ,
        0.01842168,  0.00192927, -0.02935204,  0.03410622,  0.04477049,
        0.04750114,  0.00118951,  0.04332382, -0.01832484,  0.01163442,
        0.001975

#Modeling a text dataset (setting up our modeling experiments)
***Model 0: Naive Bayes (baseline)***

***Model 1: feed-forward neural network***

***Model 2: LSTM model***

***Model 3: GRU model***

***Model 4: Bidirectional LSTM***

***Model 5: 1D Convolutional neural network***

***Model 6: Tensorflow hub  pretrained word Embedding (feature extractor)***

***Model 7: Same as model 6 but using 10% of data***

for each of these models, we're going to be following the tensorflow steps in modelling:
*construct the model

*Train the model

*Make prediction with the model

*Track prediction evaluation metrics for later comparison

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# create tokenization and modeling pipeline

model_0=Pipeline([(
    'tfidf', TfidfVectorizer()),
                  ('clf', MultinomialNB())
])


model_0.fit(train_sentences, train_labels)


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
# make predictions
baseline_preds=model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

## creating an evaluation function for our model experiments

let's make a function to evluate our modelling experimnt predictions using:
**Accuracy**

**precision**

**Recall**

**F1_score**

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):


  model_accuracy=accuracy_score(y_true, y_pred)*100

  model_precision, model_recall, model_f1, _= precision_recall_fscore_support(y_true, y_pred, average='weighted')

  model_results={'accuracy': model_accuracy,
                 'precision': model_precision,
                 'recall':model_recall,
                 'f1': model_f1}
  return model_results

In [ ]:
baseline_results= calculate_results(y_true=val_labels,
                                    y_pred=baseline_preds)
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

#Model 1: A simple dense model (feed_forward neural network)

In [ ]:
# create tensorboard callback (need to create a new one for each model)
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

from helper_functions import create_tensorboard_callback

SAVE_DIR='model_logs'

--2024-07-26 09:14:03--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py.1’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2024-07-26 09:14:03 (80.2 MB/s) - ‘helper_functions.py.1’ saved [10246/10246]



In [ ]:
train_sentences[:5]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
       "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
       'Somehow find you and I collide http://t.co/Ee8RpOahPk'],
      dtype=object)

In [ ]:
# build model with functional API
from tensorflow.keras import layers
inputs=layers.Input(shape=(1), dtype=tf.string)
x=text_vectorizer(inputs)
x=embedding(x)
x=layers.GlobalAveragePooling1D()(x)
outputs=layers.Dense(1, activation='sigmoid')(x)
model_1=tf.keras.Model(inputs, outputs, name='model_1_dense')

In [ ]:
model_1.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy']
                )
history_1=model_1.fit(train_sentences,
                      train_labels,
                      epochs=5,
                      validation_data=(val_sentences, val_labels),
                      callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                             experiment_name='model_1_dense')])

Saving TensorBoard log files to: model_logs/model_1_dense/20240726-091403
Epoch 1/5
215/215 [==============================] - 5s 18ms/step - loss: 0.6107 - accuracy: 0.6890 - val_loss: 0.5368 - val_accuracy: 0.7507
Epoch 2/5
215/215 [==============================] - 3s 16ms/step - loss: 0.4421 - accuracy: 0.8178 - val_loss: 0.4744 - val_accuracy: 0.7835
Epoch 3/5
215/215 [==============================] - 4s 17ms/step - loss: 0.3480 - accuracy: 0.8606 - val_loss: 0.4574 - val_accuracy: 0.7900
Epoch 4/5
215/215 [==============================] - 6s 26ms/step - loss: 0.2854 - accuracy: 0.8902 - val_loss: 0.4591 - val_accuracy: 0.7861
Epoch 5/5
215/215 [==============================] - 4s 16ms/step - loss: 0.2384 - accuracy: 0.9102 - val_loss: 0.4826 - val_accuracy: 0.7887


In [ ]:
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 2ms/step - loss: 0.4826 - accuracy: 0.7887


[0.4825609624385834, 0.7887139320373535]

In [ ]:
model_1_pred_probs=model_1.predict(val_sentences)
model_1_pred_probs[:10]

24/24 [==============================] - 0s 2ms/step


array([[0.35868117],
       [0.7987351 ],
       [0.99803144],
       [0.08835235],
       [0.09773903],
       [0.9346644 ],
       [0.90935516],
       [0.99229425],
       [0.95567006],
       [0.22614193]], dtype=float32)

In [ ]:
model_1_preds=tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_1_results=calculate_results(y_true=val_labels,
                                  y_pred=model_1_preds)
model_1_results

{'accuracy': 78.87139107611549,
 'precision': 0.7953441303708004,
 'recall': 0.7887139107611548,
 'f1': 0.7852145092095362}

In [ ]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

In [ ]:
import numpy as np
np.array(list(model_1_results.values()))>np.array(list(baseline_results.values()))

array([False, False, False, False])

In [ ]:
words_in_vocab = text_vectorizer.get_vocabulary()
len(words_in_vocab), words_in_vocab[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [ ]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (  (None, 128)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 128

In [ ]:
embed_weights= model_1.get_layer('embedding').get_weights()[0]
print(embed_weights.shape)

(10000, 128)


In [ ]:
import io
out_v=io.open('vectors.tsv','w', encoding='utf-8')
out_m=io.open('metadata.tsv','w', encoding='utf-8')
for index, word in enumerate(words_in_vocab):
  if index == 0:
    continue
  vec=embed_weights[index]
  out_v.write('\t'.join([str(x) for x in vec])+ '\n')
  out_m.write(word + '\n')
out_v.close()
out_m.close()

In [ ]:
try:
  from google.colab import files
  files.download('vectors.tsv')
  files.download('metadata.tsv')
except Exception:
  pass

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# model 2: LSTM
LSTM: long short term memory

In [ ]:
# create a LSTM model
from tensorflow.keras import layers
inputs=layers.Input(shape=(1,), dtype='string')
x=text_vectorizer(inputs)
x=embedding(x)
print(f'After embedding: {x.shape}')
# x= layers.LSTM(64, activation='tanh', return_sentences=True)(x)
# print (f'After LSTM cell with return_sentences= True: {x.shape})
x=layers.LSTM(64, activation='tanh')(x)
print(f'After LSTM cell: {x.shape}')
# x= layers.Dense(64, activation='relu')(x) optional dense layer to have on the top of LSTM
outputs=layers.Dense(1, activation='sigmoid')(x)
model_2=tf.keras.Model(inputs, outputs, name='model_2_LSTM')

After embedding: (None, 15, 128)
After LSTM cell: (None, 64)


In [ ]:
model_2.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

In [ ]:
history_2=model_2.fit(train_sentences,
                      train_labels,
                      epochs=5,
                      validation_data=(val_sentences, val_labels),
                      callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                             experiment_name='model_2_LSTM')])

Saving TensorBoard log files to: model_logs/model_2_LSTM/20240726-091427
Epoch 1/5
215/215 [==============================] - 11s 37ms/step - loss: 0.2176 - accuracy: 0.9273 - val_loss: 0.5821 - val_accuracy: 0.7848
Epoch 2/5
215/215 [==============================] - 6s 29ms/step - loss: 0.1552 - accuracy: 0.9426 - val_loss: 0.6488 - val_accuracy: 0.7795
Epoch 3/5
215/215 [==============================] - 13s 61ms/step - loss: 0.1303 - accuracy: 0.9523 - val_loss: 0.7482 - val_accuracy: 0.7927
Epoch 4/5
215/215 [==============================] - 9s 39ms/step - loss: 0.1063 - accuracy: 0.9604 - val_loss: 0.7641 - val_accuracy: 0.7743
Epoch 5/5
215/215 [==============================] - 6s 27ms/step - loss: 0.0849 - accuracy: 0.9676 - val_loss: 1.0127 - val_accuracy: 0.7822


In [ ]:
model_2_pred_probs=model_2.predict(val_sentences)
model_2_pred_probs.shape, model_2_pred_probs[:10]

24/24 [==============================] - 1s 5ms/step


((762, 1),
 array([[2.8972162e-03],
        [8.2222348e-01],
        [9.9978489e-01],
        [3.1322774e-02],
        [4.2061068e-04],
        [9.9936736e-01],
        [7.8486407e-01],
        [9.9984437e-01],
        [9.9970180e-01],
        [3.2076409e-01]], dtype=float32))

In [ ]:
# round out preds probs and reduce to 1-dimensional array
model_2_preds=tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_2_preds=tf.squeeze(tf.round(model_2_preds))
model_2_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_2_results = calculate_results(y_true=val_labels,
                                    y_pred=model_2_preds)
model_2_results

{'accuracy': 78.21522309711287,
 'precision': 0.7856661242905698,
 'recall': 0.7821522309711286,
 'f1': 0.7795215466562155}

#Model 3: GRU
GRU = Gated recurrent unit (one of the most popular and useful and recurrent layer types)

In [ ]:
# build an RNN using the GRU cell
from tensorflow.keras import layers
inputs= layers.Input(shape=(1,),dtype='string')
x=text_vectorizer(inputs)
x=embedding(x)
# x=layers.GRU(64, activation='tanh', return_sentences=True)(x)
# print(x.shape)
x=layers.GRU(64, activation='tanh')(x)
outputs= layers.Dense(1, activation='sigmoid')(x)
model_3=tf.keras.Model(inputs, outputs, name='model_3_GRU')

In [ ]:
model_3.summary()

Model: "model_3_GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 gru_1 (GRU)                 (None, 64)                37248     
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1317313 (5.03 MB)
Trainable params: 1317313 (5.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________

In [ ]:
model_3.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])
model_3_history=model_3.fit(train_sentences,
                            train_labels,
                            epochs=5,
                            validation_data=(val_sentences, val_labels),
                            callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                   experiment_name='model_3_GRU')])

Saving TensorBoard log files to: model_logs/model_3_GRU/20240726-092115
Epoch 1/5
215/215 [==============================] - 14s 43ms/step - loss: 0.1600 - accuracy: 0.9329 - val_loss: 0.6520 - val_accuracy: 0.7782
Epoch 2/5
215/215 [==============================] - 7s 34ms/step - loss: 0.0861 - accuracy: 0.9675 - val_loss: 0.8172 - val_accuracy: 0.7795
Epoch 3/5
215/215 [==============================] - 9s 41ms/step - loss: 0.0704 - accuracy: 0.9721 - val_loss: 0.9644 - val_accuracy: 0.7756
Epoch 4/5
215/215 [==============================] - 8s 35ms/step - loss: 0.0587 - accuracy: 0.9756 - val_loss: 0.9832 - val_accuracy: 0.7756
Epoch 5/5
215/215 [==============================] - 8s 39ms/step - loss: 0.0531 - accuracy: 0.9772 - val_loss: 1.1752 - val_accuracy: 0.7664


In [ ]:
model_3_pred_probs=model_3.predict(val_sentences)
model_3_pred_probs[:10]

24/24 [==============================] - 1s 7ms/step


array([[1.2739986e-03],
       [8.1614673e-01],
       [9.9983865e-01],
       [1.3495347e-01],
       [7.3630647e-05],
       [9.9964422e-01],
       [9.2204708e-01],
       [9.9991137e-01],
       [9.9986827e-01],
       [9.7884935e-01]], dtype=float32)

In [ ]:
# convert model 3 pred probs into labels
model_3_preds=tf.squeeze(tf.round(model_3_pred_probs))
model_3_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
# calculate the results for model 3
model_3_results=calculate_results(y_true=val_labels,
                                  y_pred=model_3_preds)
model_3_results

{'accuracy': 76.64041994750657,
 'precision': 0.7672473559947978,
 'recall': 0.7664041994750657,
 'f1': 0.7646647680054942}